### ISSUE TITLE
Exporting Arguments

### ISSUE THREAD

**Issue by Nivrod** [tobi-be/BlenderEdmExporter#10]
I am unable to export any animation with an argument higher than 18. All the rest work but from 19 and above, the arguments do not show up in the modelviewer at all.

**Comment by Nivrod** [comment]
I was trying to use it for airbrakes and refuelling probes but as I said, any number above 18 failed to be exported and didnt show up in the list or arguments

**Comment by tobi-be** [comment]
Ok i tried to export argument numbers above 18. There is no problem with that. So there must be another reason for that issue. I need more details to understand the problem. Best would be the blend file. Are there any errors or warnings during the export? Do you animate bones? Rotation scale or position? Did you try to export an animation which is working with an argument below 19 with an animation argument above 18?
