### ISSUE TITLE
Export skinnodes problems

### ISSUE THREAD

**Issue by FredStoned** [tobi-be/BlenderEdmExporter#11]
Hi Tobi....I been using your plugin with Blender and got good results.... have several planes exported to DCS and working well. EXCELLENT work!!

I have recently tried modelling some "animal" mods in Blender for the game .... followed your instructions to export skinnodes to EDM, but constantly get error message "too much weights per vertex.... limit to 4"........ .......  ...... tried numerous ways to get it to work but same error....   "I HAVE limited weights to 4 !!!!"   ..... ANYWAYs..... last night a adjusted something.... (so many things!"!~~)  and it kinda started working..... I get a very distorted animation and mesh in EDM model viewer. 

Problem is that I cannot replicate what I did and cant get it to work properly again....So..... it will export the model but not the animations...... or not work at all in model viewer...... or.... or...etc etc...

Please could you explain in fuller detail how to export skin modes....... there are so many variables and I cant work out which plays a role in the skinnodes export...... Hope you can help......

**Comment by FredStoned** [comment]
![bad export](https://user-images.githubusercontent.com/73332724/96973153-6d74dc80-150f-11eb-9b43-713ca4cc737e.jpg)


see attached!!

**Comment by tobi-be** [comment]
Hi Fredstone, did you follow the steps in the readme? The 4 weights problem comes from the fact that in DCS every vertex can be bound to maximal 4 bones (have 4 weights). So you have to limit the number of weights to 4 in Blender. You can use the Limit total- function in weightpaint view under weights after you used the parent with automatic weights function but you may have to adjust some weight painting. May be there is a good tutorial for a best practice with using only 4 weights. We have to accept this. 

Important settings:
1. Apply transformations to the mesh and the armature object. 
2. Set the rootbone to none deforming. 
3. You can try to delete all vertex groups before you use the automatic weights function. 

Here is a very simple example and the result. This is done with blender 2.90.0 Let me know if it works for you.

[skinexample.zip](https://github.com/tobi-be/BlenderEdmExporter/files/5430904/skinexample.zip)

**Comment by tobi-be** [comment]
Do you want to bring King kong to DCS?

**Comment by FredStoned** [comment]
Yup bringing Kong to DCS....this is myfirst real Mod from scratch... ww1 planes + kong + skyscraper.... bit of a laugh to start with, but become huge learning project...... all inspired by your EDM exporter for Blender   =)

**Comment by FredStoned** [comment]
OK.... shall try your demo..... give me til tomorrow.... I have worked out the issue with 4 weights.... I have to do it twice to make it apply properly..... ** shrug** .... but the deformation of the model as soon as I use a skin node and animation is ongoing.....

**Comment by FredStoned** [comment]
![kong1](https://user-images.githubusercontent.com/73332724/97054355-9089a580-157c-11eb-853b-260d5d46e57e.jpg)
![kong2](https://user-images.githubusercontent.com/73332724/97054369-967f8680-157c-11eb-8009-338af577c824.jpg)
![kong4](https://user-images.githubusercontent.com/73332724/97054375-97b0b380-157c-11eb-8130-ecf7ddd72621.jpg)

**Comment by FredStoned** [comment]
I had a beautiful animation of Kong in Blender swatting at planes... but cant get it to export properly...deforms so badly ??!

**Comment by FredStoned** [comment]
OK....your model works fine....hmmmm... I must have something wrong setup somewhere....... Shall start from scratch and see tomorrow.
PS...really appreciate your work on the exporter..... It makes DCS modelling affordable for those that cant afford the price for Max..... and Blender is so much easy to use!

**Comment by FredStoned** [comment]
![kongcrap2](https://user-images.githubusercontent.com/73332724/97055278-66d17e00-157e-11eb-9c88-dbd4f337d6c6.jpg)
![kongcrap](https://user-images.githubusercontent.com/73332724/97055283-6802ab00-157e-11eb-8617-9c738d2fa3f4.jpg)

**Comment by FredStoned** [comment]
something in the animation with the skin mode not right....... shall investigate
