### ISSUE TITLE
Tanktracks....?

### ISSUE THREAD

**Issue by FredStoned** [tobi-be/BlenderEdmExporter#15]
Tobi Hi...... I have been trying for days to get tank track animations to export to edm from Blender...... the Array and Bezier Curve method doesnt work ...... 
Can you suggest a way of animating tank tracks in Blender that will be exported to EDM

Hope you can help

**Comment by tobi-be** [comment]
Hi Fredstone,
Please open for example m-1.edm in Bazar/shapes in the Modelviewer and see how animations arguments 14 and 15 work. The tracks are modeled as non moving part. with argument 15 you can see that the tracks jump from one position to the next at the points 0.0, 0.25, 0.5, 0.75 and 1. between 0.0-0.25 and 0.5-0.75 looks the same and 0.25-0.5 and 0.75-1.0 looks the same. This is done with to identical Track meshes with slightly different uv-maps. Argvisibiltynodes are used to switch between them. i add a simple example here. 
[trackexample.zip](https://github.com/tobi-be/BlenderEdmExporter/files/5729711/trackexample.zip)

**Comment by FredStoned** [comment]
Excellent...thanks for this..... a simple render/UV switch...... of course!!!
