### ISSUE TITLE
Infantry Animations

### ISSUE THREAD

**Issue by FredStoned** [tobi-be/BlenderEdmExporter#16]
Tobi Hi.... me again!!! (sorry)
As title says..... does the EDM export of infantry animations work? I have tried numerous methods now but the animations in game all get jumbled together...... I think that it might be the DCS engine that draws all animations at the same time....... but I cannot work out how to setup my animation of infantry movement so they work in game. I am using a generic human chassis  and the GT_t.CH_t.HUMAN_ANIMATION     .

I can get one animation to work at a time in game...... i.e. running..... but when I add any other arg animation in blender... the animation in game goes crazy...... Am I missing something?
As always ... hope you can help

**Comment by tobi-be** [comment]
Hey Fredstone,
the animations sum up. You should start all animations from the rest position.

**Comment by FredStoned** [comment]
Tobi Hi...... 
I did this already. The animations definately do sum up..... 
SO...... how does ED get seperate INFANTRY animations to work without summing up.... I studied the ED infantry models and they all seem to run in the same timeline..... and I looked at the "human.lua" chassis deinitions and they define the arg values and the time that they operate... thay all cross each other at the same time... yet the model viewer ...... shows the animations working independantly...... confused!?!?

Do I have to write my own chassis definitions with my own arg definitions?

**Comment by FredStoned** [comment]
Tobi Hi...... 
I did this already. The animations do sum up..... 

SO...... how do I get seperate INFANTRY animations to work **without summing up**.... 

I studied the ED infantry models and they all seem to run on the same timeline..... and I looked at the "human.lua" chassis deinitions and they define the arg values and the time that they operate... thay all cross each other at the same time... yet the model viewer ...... shows the animations working independantly...... confused!?!?
