### ISSUE TITLE
Error in model viewer: ALERT NGMODEL Can't load lod //models/model.edm of model model.edm. Reason: Invalid link to bone.

### ISSUE THREAD

**Issue by SanikkuDesu** [tobi-be/BlenderEdmExporter#19]
As the title implies, whenever i export my model i get the error listed above from the DCS Model Viewer. This is not the first time i've exported a model into DCS but it is also the first time i am experiencing this issue. 

[Blend file for the model in question](https://drive.google.com/file/d/1UYNnr9P0evTjkfq4TG4XOFWQ15ZwxkmN/view?usp=sharing)

I'm aware the issue is definetely happening because of the use of skin node (which i am using for preference reasons), however my other attempts did not cause this and i've been able to sucessfully replace some of the aircraft in the game (TU-95 for example) aswell as make some simpler tests beforehand with pretty complex skinned animations. I am very lost and confused on what to do and i am unsure if its even my fault.

**Comment by tobi-be** [comment]
Hi, thank you for your report. One problem in the model is that every object which is a skinnode has a vertexgroup with the name "root". The root bone must be excluded from deforming skinnodes. I guess the root bone's deform property was enabled when you used the automatic weight function? Automatic weights creates vertex groups in the mesh with the names of the bones to which they are connected. The weights which the exporter uses are stored in those vertex groups. You have to make shure that there are only vertexgroups named like deforming bones. The object laser had no other vertexgroupt than "root" i removed it from export and removed the root vertex groups in the other objects and the modelviewer loads the exported model. I recommend to use Rendernodes for objects which does not have to be deformed by bones.

**Comment by SanikkuDesu** [comment]
Thank you very much! The issue has been fixed and now i can start finishing this up, clossing issue.
