### ISSUE TITLE
Adding normals to glass materials

### ISSUE THREAD

**Issue by whisky-actual** [tobi-be/BlenderEdmExporter#21]
Hi @tobi!

Fabulous work, we really appreciate your commitment at the JAS39 Community Mod! We had a question for you do: would it be possible to add a feature to the plug-in? We would like to be able to attach a normal map to a glass material. This allows having the raindrop effect when you export a cockpit model to EDM in DCS World. This seems to be done out of the box with the 3Dmax Plug-in. I am not a pro, but if you need help to dissect this feature I will be more than happy to help with the help of our modellers.

**Comment by tobi-be** [comment]
Hi whiskey,
i added it in the newest commit.
https://github.com/tobi-be/BlenderEdmExporter/tree/master/io_BlenderEdmExporter
Please replace the files in your Blender add on folder and try if it works like you need it. If yes i will create a release with it.

**Comment by whisky-actual** [comment]
Its works! Much appreciated mate!
