### ISSUE TITLE
connectors dont move with bones in animation

### ISSUE THREAD

**Issue by FredStoned** [tobi-be/BlenderEdmExporter#22]
Hi, dont know if this is Blender specific or due to the EDM exporter.... but when I bind an empty (connector) to a bone...eg a throttle handle ..... the empty moves with the bone in Blender but when exported to EDM, in game the connector doesnt move with the bone..... so I have to hunt around to find the hint in the cockpit (it is in the default position and hasnt moved with the animation)
any ideas how to fix this?
PS great job with the exporter, use it daily..... thanks so much!

**Comment by tobi-be** [comment]
Hi Fredstone,
How do you bind empties to a bone? It works fine for me!

**Comment by FredStoned** [comment]
Hey..... same as all other animations...... in Object mode, select connector and Shift select armature, go to pose mode , select bone, ctrlP.... bone relative.....   works with everything else, but not connectors.

**Comment by tobi-be** [comment]
Hi, i made a simple test and it works without problems:
https://youtu.be/B4gUp9nh-Wo

**Comment by FredStoned** [comment]
Hmm... thanks, yes yours works fine......
I have just realised that it is only some of the connectors that dont work, probably 50%..... I shall see what the difference is... thanks for the help....

**Comment by FredStoned** [comment]
Sorry... my bad...... it was the clickable def that was wrong... I hadnt made the axis updateable...... DOH....!

function default_axis_limited(hint_,device_,command_,arg_,default_,gain_,**updatable**_,relative_,arg_lim_)
default_axis_limited("Throttle", devices.ENGINE, device_commands.Throttle, 93, -1, 0.2, **true**, false, 0.8)

**Comment by FredStoned** [comment]
all good
