### ISSUE TITLE
Animation of lights

### ISSUE THREAD

**Issue by Breadmaker91** [tobi-be/BlenderEdmExporter#23]
Hi Tobi!
Just like whisky-actual said: amazing work on this plugin! You truly deserve all kinds of superlative praise for it! So thanks for your work!

Now to the issue.. It seems that it's not possible to animate lights (such as a spotlight) which makes it a bit troublesome to do things like flood lighting in a cockpit. (My workaround currently is to have about 10 different light objects set on different strength and then animate them on and off to simulate the light getting brighter).

Would it be possible to add the feature to animate the brightness value for the lights?

Once again, big thanks for a great plugin!

**Comment by tobi-be** [comment]
Hi breadmaker, 
I will check what I can do in the next time. Illuminated materials are already possible to animate. You are talking about the lights right?

**Comment by Breadmaker91** [comment]
Exactly. :)
I van animate materials that have illumination (such as instrument backlighting for example) but for lights (that use an "empty" object) I can't animate the brightness value. It can be set, but not animated.

Thanks! :)

**Comment by tobi-be** [comment]
Ok btw in which project do you want to use it?

**Comment by Breadmaker91** [comment]
Mainly for my SK60 mod. :)
