### ISSUE TITLE
Use One and only one armature 

### ISSUE THREAD

**Issue by Filipbercik** [tobi-be/BlenderEdmExporter#29]

**Comment by Filipbercik** [comment]
![image](https://user-images.githubusercontent.com/113298241/189533956-726649c6-3ac3-494d-a140-780f02f57a12.png)
okay so the thing is im making a model of a mig 29 in dcs and when i try to export it then it says "use one and only one armature, not writing" and i delete all the armatures and its the same

**Comment by tobi-be** [comment]
If you delete all armatures you don't have one Armature. See the readme there is a quick guide how to set up

**Comment by Filipbercik** [comment]
okay thanks

**Comment by Filipbercik** [comment]
but then there is an issue and it says animation not supported

**Comment by tobi-be** [comment]
This seems to be a how-to-use issue
