### ISSUE TITLE
Mismatch compare

### ISSUE THREAD

**Issue by aunoor** [tobi-be/BlenderEdmExporter#3]
String
https://github.com/tobi-be/BlenderEdmExporter/blob/0b5809cab5259db2a6a1183e0924164785120835/io_BlenderEdmExporter/edmexporter.py#L1257

must be
``` python
if c.parent_bone=="":
```
due to Blender API wiki: https://docs.blender.org/api/current/bpy.types.Object.html?highlight=parent_bone#bpy.types.Object.parent_bone

**Comment by tobi-be** [comment]
Corrected
