### ISSUE TITLE
Add object name to error string

### ISSUE THREAD

**Issue by aunoor** [tobi-be/BlenderEdmExporter#4]
Can you, please, add object name to error strings?

Like this, to example:
https://github.com/tobi-be/BlenderEdmExporter/blob/0b5809cab5259db2a6a1183e0924164785120835/io_BlenderEdmExporter/edmexporter.py#L1258
change to
``` python
print("Object "+c.name+" is not parented")
```
and 

https://github.com/tobi-be/BlenderEdmExporter/blob/0b5809cab5259db2a6a1183e0924164785120835/io_BlenderEdmExporter/edmexporter.py#L1280
change to 
``` python
print("Parent of "+c.name+" is not found")
```
It's be very helpfully on scenes with many objects.

**Comment by tobi-be** [comment]
Yes good idea
