### ISSUE TITLE
how use the exporter?

### ISSUE THREAD

**Issue by yuanjingxp** [tobi-be/BlenderEdmExporter#9]
thx contributors, but I don't known how use the exporter
you can make a tutorial ?

**Comment by El-Grajo** [comment]
Hi yuanjingxp,

I find the documentation very clear myself, in any case, you can find a little tutorial here, :

Small How to Download/Install/Export video 
https://youtu.be/SYvr_GLR2AE

More "Video Tutorials" are coming, showing: Lights, Visibility Animation, Connectors, SegmentsNodes...

I hope you find it useful :]

**Comment by yuanjingxp** [comment]
> Hi yuanjingxp,
> 
> I find the documentation very clear myself, in any case, you can find a little tutorial here, :
> 
> Small How to Download/Install/Export video
> https://youtu.be/SYvr_GLR2AE
> 
> More "Video Tutorials" are coming, showing: Lights, Visibility Animation, Connectors, SegmentsNodes...
> 
> I hope you find it useful :]

thanks very much ,i got it :+1:
